# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kassra/choreonoid-1.7.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kassra/choreonoid-1.7.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/kassra/choreonoid-1.7.0 && /usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/kassra/choreonoid-1.7.0 && /usr/bin/cpack --config ./CPackSourceConfig.cmake /home/kassra/choreonoid-1.7.0/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	cd /home/kassra/choreonoid-1.7.0 && $(CMAKE_COMMAND) -E cmake_progress_start /home/kassra/choreonoid-1.7.0/CMakeFiles /home/kassra/choreonoid-1.7.0/ext/SurenaV/CMakeFiles/progress.marks
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kassra/choreonoid-1.7.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/kassra/choreonoid-1.7.0 && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
ext/SurenaV/CMakeFiles/Surenaoffline.dir/rule:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/CMakeFiles/Surenaoffline.dir/rule
.PHONY : ext/SurenaV/CMakeFiles/Surenaoffline.dir/rule

# Convenience name for target.
Surenaoffline: ext/SurenaV/CMakeFiles/Surenaoffline.dir/rule

.PHONY : Surenaoffline

# fast build rule for target.
Surenaoffline/fast:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/build
.PHONY : Surenaoffline/fast

# Convenience name for target.
ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/rule:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f CMakeFiles/Makefile2 ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/rule
.PHONY : ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/rule

# Convenience name for target.
Surenaoffline_autogen: ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/rule

.PHONY : Surenaoffline_autogen

# fast build rule for target.
Surenaoffline_autogen/fast:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline_autogen.dir/build
.PHONY : Surenaoffline_autogen/fast

Surenaoffline_autogen/mocs_compilation.o: Surenaoffline_autogen/mocs_compilation.cpp.o

.PHONY : Surenaoffline_autogen/mocs_compilation.o

# target to build an object file
Surenaoffline_autogen/mocs_compilation.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/Surenaoffline_autogen/mocs_compilation.cpp.o
.PHONY : Surenaoffline_autogen/mocs_compilation.cpp.o

Surenaoffline_autogen/mocs_compilation.i: Surenaoffline_autogen/mocs_compilation.cpp.i

.PHONY : Surenaoffline_autogen/mocs_compilation.i

# target to preprocess a source file
Surenaoffline_autogen/mocs_compilation.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/Surenaoffline_autogen/mocs_compilation.cpp.i
.PHONY : Surenaoffline_autogen/mocs_compilation.cpp.i

Surenaoffline_autogen/mocs_compilation.s: Surenaoffline_autogen/mocs_compilation.cpp.s

.PHONY : Surenaoffline_autogen/mocs_compilation.s

# target to generate assembly for a file
Surenaoffline_autogen/mocs_compilation.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/Surenaoffline_autogen/mocs_compilation.cpp.s
.PHONY : Surenaoffline_autogen/mocs_compilation.cpp.s

sources/DCM.o: sources/DCM.cpp.o

.PHONY : sources/DCM.o

# target to build an object file
sources/DCM.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/DCM.cpp.o
.PHONY : sources/DCM.cpp.o

sources/DCM.i: sources/DCM.cpp.i

.PHONY : sources/DCM.i

# target to preprocess a source file
sources/DCM.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/DCM.cpp.i
.PHONY : sources/DCM.cpp.i

sources/DCM.s: sources/DCM.cpp.s

.PHONY : sources/DCM.s

# target to generate assembly for a file
sources/DCM.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/DCM.cpp.s
.PHONY : sources/DCM.cpp.s

sources/Link.o: sources/Link.cpp.o

.PHONY : sources/Link.o

# target to build an object file
sources/Link.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Link.cpp.o
.PHONY : sources/Link.cpp.o

sources/Link.i: sources/Link.cpp.i

.PHONY : sources/Link.i

# target to preprocess a source file
sources/Link.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Link.cpp.i
.PHONY : sources/Link.cpp.i

sources/Link.s: sources/Link.cpp.s

.PHONY : sources/Link.s

# target to generate assembly for a file
sources/Link.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Link.cpp.s
.PHONY : sources/Link.cpp.s

sources/PID.o: sources/PID.cpp.o

.PHONY : sources/PID.o

# target to build an object file
sources/PID.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/PID.cpp.o
.PHONY : sources/PID.cpp.o

sources/PID.i: sources/PID.cpp.i

.PHONY : sources/PID.i

# target to preprocess a source file
sources/PID.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/PID.cpp.i
.PHONY : sources/PID.cpp.i

sources/PID.s: sources/PID.cpp.s

.PHONY : sources/PID.s

# target to generate assembly for a file
sources/PID.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/PID.cpp.s
.PHONY : sources/PID.cpp.s

sources/Robot.o: sources/Robot.cpp.o

.PHONY : sources/Robot.o

# target to build an object file
sources/Robot.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Robot.cpp.o
.PHONY : sources/Robot.cpp.o

sources/Robot.i: sources/Robot.cpp.i

.PHONY : sources/Robot.i

# target to preprocess a source file
sources/Robot.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Robot.cpp.i
.PHONY : sources/Robot.cpp.i

sources/Robot.s: sources/Robot.cpp.s

.PHONY : sources/Robot.s

# target to generate assembly for a file
sources/Robot.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/Robot.cpp.s
.PHONY : sources/Robot.cpp.s

sources/main.o: sources/main.cpp.o

.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i

.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s

.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	cd /home/kassra/choreonoid-1.7.0 && $(MAKE) -f ext/SurenaV/CMakeFiles/Surenaoffline.dir/build.make ext/SurenaV/CMakeFiles/Surenaoffline.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... package"
	@echo "... package_source"
	@echo "... Surenaoffline"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... Surenaoffline_autogen"
	@echo "... Surenaoffline_autogen/mocs_compilation.o"
	@echo "... Surenaoffline_autogen/mocs_compilation.i"
	@echo "... Surenaoffline_autogen/mocs_compilation.s"
	@echo "... sources/DCM.o"
	@echo "... sources/DCM.i"
	@echo "... sources/DCM.s"
	@echo "... sources/Link.o"
	@echo "... sources/Link.i"
	@echo "... sources/Link.s"
	@echo "... sources/PID.o"
	@echo "... sources/PID.i"
	@echo "... sources/PID.s"
	@echo "... sources/Robot.o"
	@echo "... sources/Robot.i"
	@echo "... sources/Robot.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/kassra/choreonoid-1.7.0 && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

